---
- hosts: pis
  become: yes
  remote_user: pi

  vars_files:
    - vars.yml
    - passwords.yml

  pre_tasks:
    - name: Set the current MAC address for wlan0.
      set_fact:
        mac_address: "{{ hostvars[inventory_hostname].ansible_wlan0.macaddress }}"

    - name: Set variables based on wlan0 MAC address.
      set_fact:
        hostname: "{{ mac_address_mapping[cluster_mac_address].name }}"
        ip_address: "{{ mac_address_mapping[cluster_mac_address].ip }}"

  roles:
    - { role: peel.rpi-common }
    - { role: peel.rpi-wlan-client, client_interface: "wlan0" }
