* Raspberry Pi Wireless Cluster
The project sets up a basic wireless cluster (bramble) based upon Raspberry Pi devices using Ansible.
** Hardware setup
*** gate - wireless access point & router - hooks into local WiFi network (={{client_ssid}}=), exposes cluster internal WiFi (={{ssid}}=). Based upon Raspberry Pi B+ w/ double Edimax EW-811UN WiFi dongles
*** hellX - worker instances inter-connected wirelessly via internal network (via gate). Based upon Raspberry Pi 3 and Odroid C2 nodes
#+BEGIN_SRC
-> [gate] ->|-> [hell1]
            |-> [hell2]
            |-> [hell3] 
            |-> [hell4]
            |-> [hell5]
#+END_SRC
** Software setup
*** Flash linux distro of choice (tested with Raspbian Jessie Lite, *ArchLinuxARM*)
Install python and wireless_tools (pacman -Syu --noconfirm && pacman -S python2 wireless_tools && ln -s /usr/bin/python2 /usr/bin/python)
** Configuration
*** edit =inventory= to reflect CURRENT IP addresses of Pi devices (use ie. Fing for iOS to discover IPs)
*** edit =vars.yml= to reflect network interfaces' MAC adresses.
*** edit passwords: =ansible-vault edit passwords.yml=
** Running
*** running provisioning for
**** All nodes: =ansible-playbook -k -i inventory main.yml --ask-vault-pass=
**** Access Point nodes: =ansible-playbook -k -i inventory access_point.yml --ask-vault-pass=
**** Cluster nodes: =ansible-playbook -k -i inventory cluster.yml --ask-vault-pass=
*** reboot Raspberries =ansible pis -i inventory -a "shutdown -r now" -s=
** TODOS
*** TODO Add OLED diplay config to manager
Install pip2
Install pip2 packages
#+BEGIN_SRC
pip2 install wiringpi spidev gaugette
#+END_SRC
Clone scripts
https://github.com/guyc/py-gaugette.git
Connect OLED (see above)
Run scripts from samples/

